=== AritraDey-Dev/grafana/packages/grafana-data/src/themes/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "definitions": {
    "DeepPartial<ThemeColorsBase<ThemeRichColor>>": {
      "additionalProperties": false,
      "properties": {
        "action": {
          "$ref": "#/definitions/DeepPartial<{selected:string;selectedBorder:string;hover:string;hoverOpacity:number;focus:string;disabledBackground:string;disabledText:string;disabledOpacity:number;}>"
        },
        "background": {
          "$ref": "#/definitions/DeepPartial<{canvas:string;primary:string;secondary:string;}>"
        },
        "border": {
          "$ref": "#/definitions/DeepPartial<{weak:string;medium:string;strong:string;}>"
        },
        "contrastThreshold": {
          "type": "number"
        },
        "error": {
          "$ref": "#/definitions/DeepPartial<ThemeRichColor>"
        },
        "gradients": {
          "$ref": "#/definitions/DeepPartial<{brandVertical:string;brandHorizontal:string;}>"
        },
        "hoverFactor": {
          "type": "number"
        },
        "info": {
          "$ref": "#/definitions/DeepPartial<ThemeRichColor>"
        },
        "mode": {
          "enum": ["dark", "light"],
          "type": "string"
        },
        "primary": {
          "$ref": "#/definitions/DeepPartial<ThemeRichColor>"
        },
        "secondary": {
          "$ref": "#/definitions/DeepPartial<ThemeRichColor>"
        },
        "success": {
          "$ref": "#/definitions/DeepPartial<ThemeRichColor>"
        },
        "text": {
          "$ref": "#/definitions/DeepPartial<{primary:string;secondary:string;disabled:string;link:string;maxContrast:string;}>"
        },
        "tonalOffset": {
          "type": "number"
        },
        "warning": {
          "$ref": "#/definitions/DeepPartial<ThemeRichColor>"
        }
      },
      "type": "object"
    },
    "DeepPartial<ThemeRichColor>": {
      "additionalProperties": false,
      "properties": {
        "border": {
          "description": "Used for borders",
          "type": "string"
        },
        "borderTransparent": {
          "description": "Used for weak colored borders like larger alert/banner boxes and smaller badges and tags",
          "type": "string"
        },
        "contrastText": {
          "description": "Text color for text ontop of main",
          "type": "string"
        },
        "main": {
          "description": "Main color",
          "type": "string"
        },
        "name": {
          "description": "color intent (primary, secondary, info, error, etc)",
          "type": "string"
        },
        "shade": {
          "description": "Used for hover",
          "type": "string"
        },
        "text": {
          "description": "Used for text",
          "type": "string"
        },
        "transparent": {
          "description": "Used subtly colored backgrounds",
          "type": "string"
        }
      },
      "type": "object"
    },
    "DeepPartial<{brandVertical:string;brandHorizontal:string;}>": {
      "additionalProperties": false,
      "properties": {
        "brandHorizontal": {
          "type": "string"
        },
        "brandVertical": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "DeepPartial<{canvas:string;primary:string;secondary:string;}>": {
      "additionalProperties": false,
      "properties": {
        "canvas": {
          "description": "Dashboard and body background",
          "type": "string"
        },
        "primary": {
          "description": "Primary content pane background (panels etc)",
          "type": "string"
        },
        "secondary": {
          "description": "Cards and elements that need to stand out on the primary background",
          "type": "string"
        }
      },
      "type": "object"
    },
    "DeepPartial<{primary:string;secondary:string;disabled:string;link:string;maxContrast:string;}>": {
      "additionalProperties": false,
      "properties": {
        "disabled": {
          "type": "string"
        },
        "link": {
          "type": "string"
        },
        "maxContrast": {
          "description": "Used for auto white or dark text on colored backgrounds",
          "type": "string"
        },
        "primary": {
          "type": "string"
        },
        "secondary": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "DeepPartial<{selected:string;selectedBorder:string;hover:string;hoverOpacity:number;focus:string;disabledBackground:string;disabledText:string;disabledOpacity:number;}>": {
      "additionalProperties": false,
      "properties": {
        "disabledBackground": {
          "description": "Used for disabled buttons and inputs",
          "type": "string"
        },
        "disabledOpacity": {
          "description": "Disablerd opacity",
          "type": "number"
        },
        "disabledText": {
          "description": "Disabled text",
          "type": "string"
        },
        "focus": {
          "description": "Used focused menu item / select option",
          "type": "string"
        },
        "hover": {
          "description": "Used for hovered menu item / select option",
          "type": "string"
        },
        "hoverOpacity": {
          "description": "Used for button/colored background hover opacity",
          "type": "number"
        },
        "selected": {
          "description": "Used for selected menu item / select option",
          "type": "string"
        },
        "selectedBorder": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "DeepPartial<{weak:string;medium:string;strong:string;}>": {
      "additionalProperties": false,
      "properties": {
        "medium": {
          "type": "string"
        },
        "strong": {
          "type": "string"
        },
        "weak": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "ThemeShapeInput": {
      "additionalProperties": false,
      "properties": {
        "borderRadius": {
          "type": "number"
        }
      },
      "type": "object"
    },
    "ThemeTypographyInput": {
      "additionalProperties": false,
      "properties": {
        "fontFamily": {
          "type": "string"
        },
        "fontFamilyMonospace": {
          "type": "string"
        },
        "fontSize": {
          "type": "number"
        },
        "fontWeightBold": {
          "type": "number"
        },
        "fontWeightLight": {
          "type": "number"
        },
        "fontWeightMedium": {
          "type": "number"
        },
        "fontWeightRegular": {
          "type": "number"
        },
        "htmlFontSize": {
          "type": "number"
        }
      },
      "type": "object"
    }
  },
  "properties": {
    "colors": {
      "$ref": "#/definitions/DeepPartial<ThemeColorsBase<ThemeRichColor>>"
    },
    "name": {
      "type": "string"
    },
    "shape": {
      "$ref": "#/definitions/ThemeShapeInput"
    },
    "spacing": {
      "additionalProperties": false,
      "properties": {
        "gridSize": {
          "type": "number"
        }
      },
      "type": "object"
    },
    "typography": {
      "$ref": "#/definitions/ThemeTypographyInput"
    }
  },
  "type": "object"
}

=== AritraDey-Dev/grafana/packages/grafana-data/src/themes/themeDefinitions/g12Pastel.json
{
  "name": "Light Pastel",
  "colors": {
    "mode": "light",
    "border": {
      "weak": "rgba(200, 200, 200, 0.12)",
      "medium": "rgba(200, 200, 200, 0.20)",
      "strong": "rgba(200, 200, 200, 0.30)"
    },
    "text": {
      "primary": "rgb(50, 50, 50)",
      "secondary": "rgba(50, 50, 50, 0.7)",
      "disabled": "rgba(50, 50, 50, 0.5)",
      "link": "#7E9CCF",
      "maxContrast": "#000000"
    },
    "primary": {
      "main": "#A8DADC",
      "text": "#457B9D",
      "border": "#A8DADC",
      "name": "primary",
      "shade": "#93C9C7",
      "transparent": "#A8DADC26",
      "contrastText": "#FFFFFF",
      "borderTransparent": "#A8DADC40"
    },
    "secondary": {
      "main": "#F4A261",
      "shade": "#F2A473",
      "transparent": "#F4A26126",
      "text": "#E76F51",
      "contrastText": "#FFFFFF",
      "border": "#F4A261",
      "name": "secondary",
      "borderTransparent": "#F4A26140"
    },
    "info": {
      "main": "#B0C4DE",
      "text": "#6A8AAF",
      "border": "#B0C4DE",
      "name": "info",
      "shade": "#9BB3D2",
      "transparent": "#B0C4DE26",
      "contrastText": "#FFFFFF",
      "borderTransparent": "#B0C4DE40"
    },
    "error": {
      "main": "#F28B82",
      "text": "#F6685E",
      "name": "error",
      "border": "#F28B82",
      "shade": "#E67A75",
      "transparent": "#F28B8226",
      "contrastText": "#FFFFFF",
      "borderTransparent": "#F28B8240"
    },
    "success": {
      "main": "#81C995",
      "text": "#519657",
      "name": "success",
      "border": "#81C995",
      "shade": "#6EB780",
      "transparent": "#81C99526",
      "contrastText": "#FFFFFF",
      "borderTransparent": "#81C99540"
    },
    "warning": {
      "main": "#FFD166",
      "text": "#EFB950",
      "name": "warning",
      "border": "#FFD166",
      "shade": "#FFC34D",
      "transparent": "#FFD16626",
      "contrastText": "#000000",
      "borderTransparent": "#FFD16640"
    },
    "background": {
      "canvas": "#FFFFFF",
      "primary": "#F8F9FA",
      "secondary": "#E9ECEF"
    },
    "action": {
      "hover": "rgba(200, 200, 200, 0.16)",
      "selected": "rgba(200, 200, 200, 0.12)",
      "selectedBorder": "#FFD166",
      "focus": "rgba(200, 200, 200, 0.16)",
      "hoverOpacity": 0.08,
      "disabledText": "rgba(200, 200, 200, 0.6)",
      "disabledBackground": "rgba(200, 200, 200, 0.04)",
      "disabledOpacity": 0.38
    },
    "gradients": {
      "brandHorizontal": "linear-gradient(270deg, #A8DADC 0%, #F4A261 100%)",
      "brandVertical": "linear-gradient(0.01deg, #A8DADC 0.01%, #F4A261 99.99%)"
    },
    "contrastThreshold": 3,
    "hoverFactor": 0.03,
    "tonalOffset": 0.15
  },
  "spacing": {
    "gridSize": 8
  },
  "shape": {
    "borderRadius": 6
  },
  "typography": {
    "fontFamily": "\"Inter\", \"Helvetica\", \"Arial\", sans-serif",
    "fontFamilyMonospace": "'Roboto Mono', monospace",
    "fontSize": 14,
    "fontWeightLight": 300,
    "fontWeightRegular": 400,
    "fontWeightMedium": 500,
    "fontWeightBold": 500
  }
}

=== AritraDey-Dev/grafana/packages/grafana-data/src/themes/themeDefinitions/g12.json
{
  "name": "G12",
  "colors": {
    "mode": "dark",
    "background": {
      "canvas": "#12161A",
      "primary": "#0B0F12",
      "secondary": "#1C242B"
    },
    "text": {
      "primary": "#FFFFFF",
      "secondary": "#B7C1C8",
      "disabled": "#000FFF",
      "link": "#00ff41",
      "maxContrast": "#00ff41"
    },
    "border": {
      "weak": "#1C242B",
      "medium": "#2C363F",
      "strong": "#EF5A27"
    },
    "primary": {
      "main": "#24D3EE"
    },
    "gradients": {
      "brandVertical": "linear-gradient(0deg, #008f11 0%, #00ff41 100%)",
      "brandHorizontal": "linear-gradient(90deg, #008f11 0%, #00ff41 100%)"
    }
  },

  "shape": {
    "borderRadius": 6
  },

  "spacing": {
    "gridSize": 8
  }
}

=== AritraDey-Dev/grafana/packages/grafana-data/src/themes/themeDefinitions/space.json
{
  "name": "Space",
  "colors": {
    "mode": "dark",
    "border": {
      "weak": "#5A4C67",
      "medium": "#40334F",
      "strong": "#2E2439"
    },
    "text": {
      "primary": "#E5E5E5",
      "secondary": "#A2A2A2",
      "disabled": "#7D7D7D",
      "link": "#6A96F3",
      "maxContrast": "#FFFFFF"
    },
    "primary": {
      "main": "#2E2439"
    },
    "secondary": {
      "main": "#40334F"
    },
    "info": {
      "main": "#6A96F3"
    },
    "error": {
      "main": "#F44336"
    },
    "success": {
      "main": "#4CAF50"
    },
    "warning": {
      "main": "#FF9800"
    },
    "background": {
      "canvas": "#0D0B12",
      "primary": "#1A1425",
      "secondary": "#2B1D34"
    },
    "action": {
      "hover": "#40334F",
      "selected": "#2E2439",
      "selectedBorder": "#6A96F3",
      "focus": "#6A96F3",
      "hoverOpacity": 0.1,
      "disabledText": "#7D7D7D",
      "disabledBackground": "#2B1D34",
      "disabledOpacity": 0.38
    },
    "gradients": {
      "brandHorizontal": "linear-gradient(270deg, #6A96F3 0%, #2E2439 100%)",
      "brandVertical": "linear-gradient(0.01deg, #6A96F3 0.01%, #2E2439 99.99%)"
    },
    "contrastThreshold": 4,
    "hoverFactor": 0.07,
    "tonalOffset": 0.15
  },
  "spacing": {
    "gridSize": 8
  },
  "shape": {
    "borderRadius": 6
  },
  "typography": {
    "fontFamily": "\"Arial\", \"Helvetica\", sans-serif",
    "fontFamilyMonospace": "'Courier New', monospace",
    "fontSize": 14,
    "fontWeightLight": 300,
    "fontWeightRegular": 400,
    "fontWeightMedium": 500,
    "fontWeightBold": 700
  }
}
